services:
  orders-db:
    container_name: orders-db
    image: postgres:17.5
    volumes:
      - ./orders-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
